### ISSUE TITLE
Packages response from GTK not working on SON-GUI

### ISSUE THREAD

**Issue by dang03** [sonata-nfv/son-gkeeper#310]
In SON-GUI, under Catalogues -> Packages, no package is shown even if there are package descriptors stored in the Catalogue.
The source of the problem is that SON-GUI is querying Gatekeeper (GTK) on http://sp.int3.sonata-nfv.eu:32001/packages, and GTK is returning the 'son-package' file, which is binary-data. Instead, GTK should return the package descriptor (manifest).
Also point the need of differentiate son-package file and package descriptor. From the Catalogue point of view this is dealt with:

/catalogues/packages -> package descriptor
/catalogues/son-packages -> package file

**Comment by jbonnet** [comment]
@dang03 Note that theres' still this pull#282.
The empty list of packages is because we used to have a feature that returned a package file when the result of a search was a single package. I've talked to @trakadasp and @wtaverni in Brussels, and we've decided to remove that (see #294). I thought I had succeeded, but the problem still persists.

**Comment by dang03** [comment]
Thank you @jbonnet , I was not aware of this. I'm going to check it and try to fix it.

**Comment by dang03** [comment]
This issue has been addressed and fixed. Now SON-GUI shows all available packages in the Catalogues.
