### ISSUE TITLE
Incorporate licence type into licence

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#394]
Due to the simplification we have decided in Licence Management (only `Public` or `Private` types of licence, the later also having a validating `URL` to be called for every service/function download or service instantiation), I think that the current approach is an overburden.

How about adding a `licence_type` field, default to `public`, and a `validation_url` field (names are just suggestions, the latest being mandatory for `licence_type=private`) to `licences` entity?

Thanks,

**Comment by bsilvr** [comment]
Hi,

I'm sorry for the delayed response. I was doing the requested changes and came across a few doubts:
- Is the validation_url just for validating the license or does it also needs to called when a licensed is cancelled, suspended...
- Does license renewal still exist? if so do i need to call the url in some matter to notify? Because otherwise licenses would never expire. Also if it exists it could only be for private licenses, public licenses would never expire.
- Does license suspending and cancelling still exists for public licenses?

**Comment by bsilvr** [comment]
Hi,

I'm sorry for the delayed response. I was doing the requested changes and came across a few doubts:

Is the validation_url just for validating the license or does it also needs to called when a licensed is cancelled, suspended...
Does license renewal still exist? if so do i need to call the url in some matter to notify? Because otherwise licenses would never expire. Also if it exists it could only be for private licenses, public licenses would never expire.
Does license suspending and cancelling still exists for public licenses?

Thanks,

**Comment by bsilvr** [comment]
Hi,

I'm sorry for the delayed response. I was doing the requested changes and came across a few doubts:

- Is the validation_url just for validating the license or does it also needs to called when a licensed is cancelled, suspended...
- Does license renewal still exist? if so do i need to call the url in some matter to notify? Because otherwise licenses would never expire. Also if it exists it could only be for private licenses, public licenses would never expire.
- Does license suspending and cancelling still exists for public licenses?

Thanks,

**Comment by jbonnet** [comment]
Hi,

I'm sorry, I've answered this by email on the 8th Feb, but it seems it didn't go through:

> Hi, Bruno,
>* validation_url also needs to be called for every cancelation or suspension (let’s simplify things and just consider Active or Canceled licences, ok? I.e., no Suspended)
>* as stated above, I’d keep it simple: no renewals; if we want to ‘expire’ a licence, we just cancel it (do you see any unwanted consequence of this that I’m not seeing?), you must be able to still cancel a Public licence (e.g., you want o make it Private);
>* yes

Do you need any help? Is there still any doubt?
Thanks,

**Comment by bsilvr** [comment]
Hi,

One last doubt what's the difference in the call to validation_url between a validation and a canceling? For example validating is a GET while canceling is some other method? how should it be done?

As for the rest everything seems ok :)

Thanks,

**Comment by jbonnet** [comment]
Hi,
Canceling can be a PUT in a ‘status’ (e.g.) attribute. It could be a DELETE also… at the moment, there’s no difference (i.e., I don’t see how we could re-use anything if we simply DELETE a licence)...

**Comment by jbonnet** [comment]
Closed by #418
