### ISSUE TITLE
Include debugging level in the configuration file

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/son-gkeeper#415]
Debugging level (`:debug`) is currently hardcoded, and should be configurable.

**Comment by jbonnet** [comment]
Closed by #416

**Comment by felipevicens** [comment]
@jbonnet Could we pass the option through container ENV variables?

**Comment by felipevicens** [comment]
@jbonnet I've notice that you create a text-plain file for the logs generated by the application. Theses logs are stored inside the container consuming disk resources.
What do you think if we centralize the logs in a folder and mount a external volume to store it? by this way we can rotate this logs and from the point of view IT Operations would be simple to read the logs in the local server folder as /var/log/sonata/son-gk***.log
On the other hand, can we create duplicate the logging output and save it in a file that is a simbolic link to /dev/stdout? by this way if the Platform Operator decide to use a centralize logging system will be able to do it because all the logs will be redirected to standard docker logging system.

**Comment by jbonnet** [comment]
Hi, @felipe,

It is already by ENV variable LOGGER_LEVEL, defaulting to ‘debug’.

**Comment by jbonnet** [comment]
Sure, @felipevicens,
But I didn’t understand the requirement; do you want to

	1. log to the stdout?
	2. log to /var/log/sonata/son-gk***.log?
	3. both?

Thanks,

**Comment by felipevicens** [comment]
@jbonnet Should be option 3. both

**Comment by jbonnet** [comment]
Sure, @felipevicens, opening a new issue
