### ISSUE TITLE
Undefined method on POST /api/v2/requests

### ISSUE THREAD

**Issue by tobiasdierich** [sonata-nfv/son-gkeeper#919]
Hi,

I'm currently working with the SONATA project as a part of my bachelor's thesis. I'm trying to instantiate a service by making a POST request to `/api/v2/requests` with the following payload:

```
{
	"service_uuid": "fc1bf15b-6256-4d36-ac51-44af743db0c2",
	"ingresses": [],
	"egresses": []
}
```

However, the son-gtkapi always returns a the following error:
```
{
    "error": {
        "code": 500,
        "message": "#<NoMethodError: undefined method `call' for :kpi_method:Symbol>"
    }
}
```

Here's the log output:
```
D, [2017-10-06 14:49:18#6] DEBUG -- GtkApi::POST /api/v2/requests/: entered with params={"service_uuid"=>"fc1bf15b-6256-4d36-ac51-44af743db0c2", "ingresses"=>[], "egresses"=>[]}
D, [2017-10-06 14:49:18#6] DEBUG -- GtkApiHelper.require_param: param=service_uuid, params={"service_uuid"=>"fc1bf15b-6256-4d36-ac51-44af743db0c2", "ingresses"=>[], "egresses"=>[], "request_type"=>"CREATE"}
D, [2017-10-06 14:49:18#6] DEBUG -- GtkApiHelper.require_param: param=egresses, params={"service_uuid"=>"fc1bf15b-6256-4d36-ac51-44af743db0c2", "ingresses"=>[], "egresses"=>[], "request_type"=>"CREATE"}
D, [2017-10-06 14:49:18#6] DEBUG -- GtkApiHelper.require_param: param=ingresses, params={"service_uuid"=>"fc1bf15b-6256-4d36-ac51-44af743db0c2", "ingresses"=>[], "egresses"=>[], "request_type"=>"CREATE"}
E, [2017-10-06 14:49:18#6] ERROR -- : {"error":{"code":500,"message":"#<NoMethodError: undefined method `call' for :kpi_method:Symbol>"}}
```

I've tested the containers with the tags `latest`,  `dev` and `3.0`, all throwing the exception above.

Is this a known issue (somewhat related to #821) or am I doing something wrong ?

Best regards,
Tobias

**Comment by jbonnet** [comment]
Hi, Tobias,Thanks for having downloaded SONATA and trying it! Apparently you did everything right, but at the moment I'm not able to access the code, since I'm on a business travel. but I'll take a look at it ASAP and let you know.José Em 06/10/2017 17:19, Tobias Dierich <notifications@github.com> escreveu:Hi,
I'm currently working with the SONATA project as a part of my bachelor's thesis. I'm trying to instantiate a service by making a POST request to /api/v2/requests with the following payload:
{
	"service_uuid": "fc1bf15b-6256-4d36-ac51-44af743db0c2",
	"ingresses": [],
	"egresses": []
}

However, the son-gtkapi always returns a the following error:
{
    "error": {
        "code": 500,
        "message": "#<NoMethodError: undefined method `call' for :kpi_method:Symbol>"
    }
}

Here's the log output:
D, [2017-10-06 14:49:18#6] DEBUG -- GtkApi::POST /api/v2/requests/: entered with params={"service_uuid"=>"fc1bf15b-6256-4d36-ac51-44af743db0c2", "ingresses"=>[], "egresses"=>[]}
D, [2017-10-06 14:49:18#6] DEBUG -- GtkApiHelper.require_param: param=service_uuid, params={"service_uuid"=>"fc1bf15b-6256-4d36-ac51-44af743db0c2", "ingresses"=>[], "egresses"=>[], "request_type"=>"CREATE"}
D, [2017-10-06 14:49:18#6] DEBUG -- GtkApiHelper.require_param: param=egresses, params={"service_uuid"=>"fc1bf15b-6256-4d36-ac51-44af743db0c2", "ingresses"=>[], "egresses"=>[], "request_type"=>"CREATE"}
D, [2017-10-06 14:49:18#6] DEBUG -- GtkApiHelper.require_param: param=ingresses, params={"service_uuid"=>"fc1bf15b-6256-4d36-ac51-44af743db0c2", "ingresses"=>[], "egresses"=>[], "request_type"=>"CREATE"}
E, [2017-10-06 14:49:18#6] ERROR -- : {"error":{"code":500,"message":"#<NoMethodError: undefined method `call' for :kpi_method:Symbol>"}}

I've tested the containers with the tags latest,  dev and 3.0, all throwing the exception above.
Is this a known issue (somewhat related to #821) or am I doing something wrong ?
Best regards,
Tobias

**Comment by jbonnet** [comment]
Hi, @tobiasdierich 
I think PR #920 has fixed the bug, but please retry and let me know.

Thanks again,

**Comment by tobiasdierich** [comment]
Hi,
PR #920 fixed this issue, thanks.

Best regards,
Tobias
